module.exports = {
  WAITING_TO_ACCEPT: 'WAITING_TO_ACCEPT',
  PLAYER1_TURN: 'PLAYER1_TURN',
  PLAYER2_TURN: 'PLAYER2_TURN',
  PLAYER1_CHAR_SELECT: 'PLAYER1_CHAR_SELECT',
  PLAYER2_CHAR_SELECT: 'PLAYER2_CHAR_SELECT',
  COMPLETED: 'COMPLETED',
}
